addons:
  sauce_connect: true
node_js:
    - "7"
install:
  - npm install -g nightwatch
before_script:
  - npm run serve:dist &
script:
  - nightwatch --test ./test/e2e/test.js --config ./nightwatch.js,
  - pkill node
